### ISSUE TITLE
[Feature Request] Use Google AMP

### ISSUE THREAD

**Issue by insign** [HermanMartinus/bearblog#101]
Google AMP can speedup access in some ways. There some drawbacks like AMP rules, but I think using a AMP compatible can make a big difference in UX.

**Comment by rkingett** [comment]
I think Google is getting rid of AMP so it might not even be worth looking into. Personally, I don't want this at all because the blogs are pretty speedy even without AMP.

**Comment by HermanMartinus** [comment]
As @rkigett mentioned, Google is potentially getting rid of AMP (and is notorious for deprecating stuff). Bear is built with tools that will hopefully be around 20-30 years from now. Currently Bear is also super speedy and accessible (mostly due to the ~5kb pagesize and CDN) so I don't think the performance gain will have that much of an effect.
