### ISSUE TITLE
Embedded content not being displayed

### ISSUE THREAD

**Issue by Sush-ruta** [HermanMartinus/bearblog#104]
Hi,

I tried to embed a SlideShare presentation in my post using the ``<iframe>`` tag, but it did not show up on the post. Tried embedding using the ``<embed>`` tag with same result. All the other HTML tags work as far as I have tried, except embedding.

Thanks for making and maintaining Bearblog, btw. :)

**Comment by HermanMartinus** [comment]
Hey @Sush-ruta, currently Bear strips out iframes and any JS (for security and simplicity reasons). I think it may be a good idea to only limit that to only JS. I'll tinker with this and see if that's a workable solution and update this issue later today or tomorrow (hopefully).

**Comment by HermanMartinus** [comment]
I've added the ability to add iframe from certain whitelisted sites. You can add your slideshare iframe, just note that the `src` attribute needs to be explicit about the protocol. This means when you paste the embed code, make sure that `src` starts with `https://slideshare.net` instead of `//slideshare.net`. 

Currently only Youtube, Slideshare and Vimeo are whitelisted. For additional whitelist suggestions open a new issue :)

**Comment by jziggas** [comment]
Hello! The concept/feature of embedding would also apply to things like Stackblitz and Codepen right?

**Comment by HermanMartinus** [comment]
Just added Codepen and Stackblitz to the whitelist. You'll need to select the `iframe` option for this :)
