### ISSUE TITLE
A custom favicon support

### ISSUE THREAD

**Issue by Disil** [HermanMartinus/bearblog#112]
I think it would be great if bearblog has support for custom favicon, right now it only supports emoji.

**Comment by Cwpute** [comment]
i think the main objective behind allowing only emojis as favicons makes it a lot less heavy on the server hosting images for each blog. also, emojis (i think) can be loaded from the computer itself rather than a server, thus a lesser waste of data.
This is the pov of a very uneducated guy on this subject 😅

**Comment by Disil** [comment]
Well we don't need the ability to 'host' icon. Just allow user to embed icon from different website (e.g imgur).

**Comment by HermanMartinus** [comment]
I'll pop it under consideration, but not prioritized 👍

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
