### ISSUE TITLE
Please add other options for donations

### ISSUE THREAD

**Issue by ghost** [HermanMartinus/bearblog#116]
Hey, great project. Do you think it would be possible to add other options for donations than PayPal? PayPal is a nuisance... It's not possible for me to donate without an account and giving them my phone number.

There are many other services where you could create an account and accept payments with credit cards that don't go through PayPal: [liberapay.com](https://liberapay.com), [ko-fi.com](https://ko-fi.com), [opencollective.com](https://opencollective.com), [patreon.com](https://www.patreon.com). I think it's even possible to donate/support to a project directly on GitHub.

Just an idea.

**Comment by Cwpute** [comment]
I'd donate some via ko-fi or liberapay if you ever consider setting up an account on there !

**Comment by HermanMartinus** [comment]
Thanks for the support :) The issue I have with GitHub sponsors, as well as a few other methods is that I can't open a Stripe account as it's not available in South Africa just yet. PayPal is pretty awful but universal. 

I've just set up a Ko Fi account https://ko-fi.com/herman_the_merman

Let's see if that works (under the surface is still PayPal since I can't open a Stripe account, but maybe they handle the payments asymmetrically).

**Comment by HermanMartinus** [comment]
Leaving this card open to remind me to add this link to the contribute page.

**Comment by HermanMartinus** [comment]
The new contribute/upgrade supports multiple payment methods that should work universally (hopefully)
