### ISSUE TITLE
Custom favicons no longer work

### ISSUE THREAD

**Issue by y-arjun-y** [HermanMartinus/bearblog#145]
As an example, [herman.bearblog.dev](https://herman.bearblog.dev) previously had the koala emoji as its favicon, but now it's the default white Bear Blog favicon. Custom favicons no longer work [on my website](https://arjunyadav.net) and, on browsing through the discovery feed, I could not find any custom favicons.

**Comment by HermanMartinus** [comment]
Looking into it now. I added a fallback favicon for Safari recently (since the emoji favicon wasn't working on it) but it seems to have fixed it for Safari and broken it for Chrome. 🥲

Will rectify today.

**Comment by HermanMartinus** [comment]
Fixed in f923026ce3ade6a358bd158341b6a998cf9ba62a and df0ffb3efca6b74d0b0ebaed811ca74041e0c37b

It turns out with Chrome you need to specify the size in order to reduce the `.ico` priority over the svg (emoji). 

Please close this issue if it works for you (you may need to do a hard reload since favicons cache quite hard).

**Comment by y-arjun-y** [comment]
Works, thank you!
