### ISSUE TITLE
importing google fonts in css may not be working?

### ISSUE THREAD

**Issue by james-see** [HermanMartinus/bearblog#152]
I can't tell if it is working or not. `@import url('https://fonts.googleapis.com/css?family=Muli&display=swap');` for example does not seem to work.

**Comment by y-arjun-y** [comment]
Importing Google Fonts is working just fine for me when I use an external CSS file or extend/overwrite existing styles. The font you gave also works for me. How are you going about using the font? Maybe a screenshot of your styling page could help out.

**Comment by y-arjun-y** [comment]
Apologies, **extending styles seems to break importing Google Fonts.** Though I'm not exactly sure why. For now, I'd recommend using 'Overwrite styles' or a CDN link. Hope that fixes your issue!

**Comment by HermanMartinus** [comment]
Looking into it 👍

**Comment by HermanMartinus** [comment]
@constantskeptic you're not crazy 😄 it seems when extending it breaks the import, but them overwriting it works fine. Going to try push a fix now.

**Comment by HermanMartinus** [comment]
As with some things, it turns out it's more complicated than what meets the eye. It turns out that `@import` needs to be at the top of the css file, however, to extend css (by virtue of it 'cascading') the custom style needs to be added to the end. This means in order to import fonts I'll need to build out an additional field called 'import fonts'.

I'll add this to my list of things to consider, but in the meantime, you can just copy the base css from [here](https://github.com/HermanMartinus/bearblog/blob/master/templates/styles/main.css), select "Overwrite styles", and modify it as you see fit.

**Comment by HermanMartinus** [comment]
In the above css file you can ignore everything from `footer` downwards (line 153) as those are dashboard specific styles.

**Comment by HermanMartinus** [comment]
Just doing some cleanup here. The styles are now a bit more advanced. What I'd suggest doing to get around this is to have custom styling replace instead of extend the default stylesheet. This way the `@import` statement at the top of the stylesheet will work perfectly.
