### ISSUE TITLE
How do I add sitemaps?

### ISSUE THREAD

**Issue by avinashkanaujiya** [HermanMartinus/bearblog#167]
So that Google can index my blog properly.

**Comment by HermanMartinus** [comment]
There are currently no sitemaps and Google indexes stuff quite fine, but it is good practise. I'll add it to the next release 👍

**Comment by HermanMartinus** [comment]
Sitemaps have been added in bec2c759639888b933dc8dc019d4a52f47921593

They are available on all blogs at `/sitemap.xml` eg: https://herman.bearblog.dev/sitemap.xml

**Comment by ok4ib** [comment]
I added the sitemap but google says it is in the wrong formatting. Probably this is because the formatting Herman implemented is linear. Could you please fix it?

**Comment by HermanMartinus** [comment]
Can you let me know what tool you're using to validate your sitemap? The only issue Google Search Console had with the existing one was the date format for `lastpub` (which has since been rectified). 
![Screenshot 2022-10-04 at 08 54 24](https://user-images.githubusercontent.com/26326265/193753998-2c9d8dd8-409f-4b84-8e6a-4a2437d93e2d.png)
