### ISSUE TITLE
Footer content should be HTML

### ISSUE THREAD

**Issue by vprelovac** [HermanMartinus/bearblog#198]
Currently site footer setting is not HTML (or markdown) aware so one can not have links in footer for example.

**Comment by HermanMartinus** [comment]
Added to my list today 👍

**Comment by HermanMartinus** [comment]
I've given this some serious consideration and even built out the functionality for adding an HTML/Markdown footer, however, I  decided that  simply editing the **post template** to add footer content so it's created anew for each post/page is actually a more elegant solution. This allows more control over the page footer content as you can change the footer for a specific page if necessary. 

Eg: On [my blog](https://herman.bearblog.dev/building-software-to-last-forever) I've added: "I write about 1-2 articles a month. Subscribe via email or RSS feed." as a footer, but some pages I don't want this footer so I can remove it, instead of it being mandatory. 

This allows for more flexibility while retaining the same baseline functionality and reducing complexity. If you'd like to just remove the "Made with Bear" footer this can be done easily enough with CSS, although I encourage people to keep the link :)

**Comment by gokceozan** [comment]
> simply editing the post template to add footer content so it's created anew for each post/page is actually a more elegant solution

But that would mean if you want to edit the footer, then you have to edit all your posts. Which makes it extremely unpractical, no?

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io/). Github issues reserved for bugs going forward.
