### ISSUE TITLE
Getting 404 error for all my posts

### ISSUE THREAD

**Issue by crptbnd** [HermanMartinus/bearblog#203]
Hello. I created some posts and was able to access each of them. But a while ago I started getting 404 error for each of my posts. I see posts in editor and I am able to edit and publish posts.

**Comment by HermanMartinus** [comment]
Pop me an email with your blog subdomain. I think your blog was probably flagged as spam (the bane of free services on the internet).

**Comment by crptbnd** [comment]
Hello, Herman.

cryptoband is subdomain

Ср, 21 дек. 2022 г. в 15:07, Herman ***@***.***>:

**Comment by HermanMartinus** [comment]
Most crypto trading content is blocked by the spam checker. I've taken a look at your blog and it may violate the policy of spamming or deceptive linking since it seems to be trying to sell a crypto trading algorithm. You can send me an email to appeal this block if you believe I've made an error in my judgement.
