### ISSUE TITLE
Why Blog title on posts is an h1?

### ISSUE THREAD

**Issue by strdr4605** [HermanMartinus/bearblog#214]
Shouldn't a blog post have only one h1 tag that indicated the title of the content?
Maybe SEO does not care that much about this nowadays.
But there is a common practice for pages that have content and a title.

Why this is a problem for me?:
I add things I read to a reading list. And I query for h1. For bearblog articles, I get the blog's title instead of content title.
Here is my check `"${document.querySelector("h1")?.innerText || document.title}"`.
Change my mind to reverse the condition 😅

**Comment by HermanMartinus** [comment]
Heh, this has been discussed in a previous issue. The conclusion is that there are no negative consequences of having both the blog and article titles as `h1` elements, even if that was previously considered bad practice. Search engines have become a lot smarter. The issue is that by changing the blog title to another element it breaks many blog's custom styling (if they use the h1 selector). Due to this it's not worth the hassle to change it for very minimal (or no) upside (although I am sorry that it doesn't cater to your reading list scraper) 😅
