### ISSUE TITLE
Text editor font and saving attributes problem. 

### ISSUE THREAD

**Issue by focarafa** [HermanMartinus/bearblog#234]
Hey Guys,

I'm not the tech guy, so I don't even know if this is a bug or some kind of update and design choice.

Since yesterday, my dashboard interface went weird. I'm using Firefox, tried Edge, Chrome, and even mobile browsers.

I'm also experiencing problems saving attributes like "tags". 

Sorry for the dumb question, but can someone help me with this?

![image](https://github.com/HermanMartinus/bearblog/assets/87738617/7b0452d0-b1ae-4dae-b395-01f25524aa94)
![image](https://github.com/HermanMartinus/bearblog/assets/87738617/f5f54844-3311-48a9-8e99-3f74a59b1163)

**Comment by HermanMartinus** [comment]
Hey there, not a dumb question at all. I did a bunch of cleanup last week of the editor (I had two running in parallel and decided to deprecate the unused one. 

- Saving of tags has been fixed (that was my bad)
- The font has been returned to Verdana in the editor
- There is now a hard separation between the header options (attributes) and the body content since too many people were accidentally breaking their pages. 


Please feel free to get in touch if you have any other problems with the editor updates :)
