### ISSUE TITLE
feature: allow private blogs

### ISSUE THREAD

**Issue by rishyak** [HermanMartinus/bearblog#272]
It would be neat if it was possible to mark blogs as private so they don't appear on the `/blog/` page. 

I understand this feature can be emulated by not exposing `/blog/` on your navbar. 

Here's what I came up with:
- Remove `/blog/` from your nav bar
- Religiously use tags in your posts
- Embed blog post lists ({{ posts|tag:"news" }}`) in various pages

However, it's a fairly cumbersome process, and anyone can just go to `/blog/`, which defeats the purpose. 

Instead, being able to mark some posts as private to prevent them from being seen on the post list would be quite nice. I know that this can also be emulated by making multiple "pages". However, that prevents using cool Bearisms like embedding post lists.

Here are a few neat features this "private" feature could have:
- Prevents web crawling
- Not discoverable by default

**Comment by HermanMartinus** [comment]
Hey @rishyak, if you set the `is_page: true` attribute for a post it will behave as described. This won't show up in your posts feed or using the embedded post list, since the blog treats it as a page. 

In terms of preventing web crawling you can set that by modifying the robots.txt file in **Settings/Advanced Settings** in your dashboard. 

Thanks for the suggestions, but for future suggestions please use the [feature request board](https://bear.nolt.io). I like to keep Github issues for bugs :)
