### ISSUE TITLE
CDN not available for custom domains

### ISSUE THREAD

**Issue by pimoore** [HermanMartinus/bearblog#284]
Doing testing via webpagetest.org reveals that Bear blogs using a custom domain aren't using the Cloudflare CDN as the bearblog.dev ones are. Is this a bug, or is there a workaround to ensure the CDN continues to work for those using custom domains? In the example below the person has their own pull zone setup for a web font, but the domain itself has no CDN linked to it.

![IMG_0289](https://github.com/HermanMartinus/bearblog/assets/5413470/a2986f9d-0780-412f-a943-4160eb188b09)
![IMG_0290](https://github.com/HermanMartinus/bearblog/assets/5413470/a79f8745-1d12-40a9-ac09-48d32d43ec1e)

**Comment by HermanMartinus** [comment]
Well spotted. 

Cloudflare adds a CDN on the domain level, and so all the subdomains (*.bearblog.dev) are covered by the Cloudflare CDN. You can set up Cloudflare CDN for your blog by using Cloudflare to manage your domain, and ensuring your SSL/TLS encryption mode is `Full (strict)`. You can see this running at [this demo blog](https://blog.justcors.com).

This will give a tiny bump in performance, but for simplicity sake I recommend most people ignore adding a CDN since it doesn't materially affect performance (the page size is generally <5kb), images and fonts are behind a CDN already, and my reverse proxy issues a Let's Encrypt certificate so https is ensured.
