### ISSUE TITLE
i could like my own blog more than once

### ISSUE THREAD

**Issue by ShravannJain** [HermanMartinus/bearblog#314]
whenever i write my blog i head to other blogs which were already written i could like it even if i already liked that blog

**Comment by HermanMartinus** [comment]
Bear is built so that people can upvote a post even if they don't have an account. This is done by taking a hash of the IP address. If you can re-upvote your post it means you're viewing the post from another IP address and it sees you as a separate person. 

There are tradeoffs to this method, but it's better than cookies, requiring signins, etc. So this functionality is by design, but not perfect. If you have an idea on how to make this better, please let me know :)
