### ISSUE TITLE
New post via CURL?

### ISSUE THREAD

**Issue by aaronpkelly** [HermanMartinus/bearblog#39]
Hey - is it possible to submit a new post programmatically - e.g. via a CURL command? Or maybe there is an API available?

**Comment by HermanMartinus** [comment]
Currently there isn't an api available, but I've added it to the roadmap :)

**Comment by ulpaulpa** [comment]
[micropub](https://micropub.net/) is an open protocol for creating posts.

**Comment by strdr4605** [comment]
Any updates on this?

**Comment by alexkolson** [comment]
Hey @HermanMartinus absolutely <3 bearblog! Thank you so much for making it! Just adding my voice to others wishing for an api. For me, it is because I write in google docs, and then copy and paste everything over into bearblog. It would be really cool to automate this process, and I think a general purpose api would be perhaps one of the best ways to do so. I wouldn't be against an "Import from Google Docs" button either, but see more value as an end-user from a general-purpose api. Either way, thank you again and I realize you owe us absolutely nothing. Whatever you end up deciding, I'll be here for the ride!

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
