### ISSUE TITLE
[Feature Request] Single page posts view (infinite scroll)

### ISSUE THREAD

**Issue by dimnls** [HermanMartinus/bearblog#65]
Congrats for the concept and execution 👌Truly an elegant, minimal way to blog.
I understand you want to focus more on lengthier blog posts, but I think the minimalism of BearBlog would go well with a single page view such as 

# Title 1
> Short content of blogpost 1

# Title 2
> Short content of blogpost 2

Simply because going to a person's "blog" page, clicking the titles, reading the content, and going back to repeat, is not always very practical.

**Comment by HermanMartinus** [comment]
That's actually a pretty neat idea. I'll put it on my list to investigate.

**Comment by dimnls** [comment]
Nice, looking forward to it!

**Comment by nodeMD** [comment]
I like that idea, but I also like the current approach. Maybe give the creator of the blog a way to choose which option he want to use (single page or with blog subpage). For now creators of the blog posts may add a simple table with links to previous and next posts:
```
|[Prev](/prevPostPermalink)|[Next](/nextPostPermalink)|
| --------- | --------- |
```
which, I think, will result in better end user experience. 
Or the creator can just update Dashboard with a new short posts in a way proposed by dimnls. 
# Title 1
> Short content of blogpost 1

# Title 2
> Short content of blogpost 2
Then everything will be on a single page. So that may be the current workaround for single page blog.

**Comment by HermanMartinus** [comment]
Moved to the [new suggestion board](https://bear.nolt.io). Github issues reserved for bugs going forward.
