### ISSUE TITLE
404 page uses default stylesheet

### ISSUE THREAD

**Issue by yunruse** [HermanMartinus/bearblog#81]
I'm not sure if this is intentional or not, but it's a little jarring that a 404 moves to a different stylesheet and uses the Bear Blog links. While the table-flipping bear is cute (and I wouldn't want to change that), it would be nice to keep the styling consistent.

**Comment by HermanMartinus** [comment]
Since the 404 page doesn't necessarily have the blog information (it's generic for either posts not found, blogs not found, or Bear's website content not found) it can't actually pull in the blog's styling info as it may not have it. What I have gone and done in 51d282357df29e61c3d0388fe94671498c059f25 is to simplify the 404 page a decent amount so it should work better as a generic page whether on a user blog or not. 

I hope this is a good concession :)
